# backend-ci.yml
name: Build and Push backend Image only when there is a code changes
run-name: ${{ github.actor }} Build and Push backend Image to dockerhub

on:
    push:
        branches:
            main
        paths: 
        - 'backend/**' # Trigger only when changes are made in the backend directory
    pull_request:
        branches:
            main
        paths: 
        - 'backend/**'

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: backend

    #   Run backend test
      - name: Run backend tests
        run: npm test
        working-directory: backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Express app - ecommerce-backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest